### ISSUE TITLE
Kyle!! What's up!! I haven't been on Github in a while, I saw you started a new LOL project and saw this. 

### ISSUE THREAD

**Issue by Kyle-Ski** [kDurg/LoLv2#1]
Looks like there might be an api key in here 😬 Please disregard if I have no idea what I'm talking about 😅 
https://github.com/kDurg/LoLv2/blob/3b2e9fe44b0eff1046d18ae6db47b8e1b128ade5/server.js#L10

**Comment by kDurg** [comment]
SKI!!!! Good to see your message! Thanks for the heads up! The Riot key is only active for a short time which should prevent anything from happening, though I will move it is a .env file once I get some basic functionality going. Thanks for the heads up!
